### ISSUE TITLE
resources/application.properties

### ISSUE THREAD

**Issue by hwb1992** [hot13399/companyname-projectname-mocr#4]
hi,where is the resources/application.properties ?
i start this project ,but there is error that "Caused by: java.io.FileNotFoundException: resources\application.properties"
thanks .

**Comment by zplogo** [comment]
I also encounter this problem have you solved?

**Comment by hwb1992** [comment]
no..

**Comment by F4bwDP6a6W** [comment]
how did you run this project? By maven? maven will look into resources folder.

**Comment by hwb1992** [comment]
Yes.I import as a maven project.My IDE is idea.
Does this file exist in "/spring-mvc-mini/blob/master/resources/application.properties"???
If yes.Wny not move this file into "src/main/resources/application.properties"?
